#Vars for readability
CMD = g++
CMFLAG = -Wall -std=c++11
TARG = Chess

#Targets for exe file.
$(TARG): $(TARG).o Board.o
	$(CMD) $(CMFLAG) -o $(TARG) $(TARG).o Board.o
$(TARG).o: $(TARG).cpp Board.hpp
	$(CMD) $(CMFLAG) -c $(TARG).cpp Board.hpp
Board.o: Board.cpp Board.hpp
	$(CMD) $(CMFLAG) -c Board.hpp Board.cpp

clean:
	del /q *.o
spal:
	cls
	make
	make clean
	cls 
	$(TARG)
run:
	make
	cls
	$(TARG)
text:
	$(TARG) >> $(TARG).txt
